FROM chetansinghsajwan/atom_core:dev

ENV CMAKE_EXPORT_COMPILE_COMMANDS="True"

ARG RAPIDJSON_VERSION="v1.1.0"
ARG OPENSSL_VERSION="3.5.0"

# Installing rapdijson, required by pistache
RUN git clone "https://github.com/Tencent/rapidjson" \
    --depth 1 --branch $RAPIDJSON_VERSION \
    && cd rapidjson \
    && cmake -S . -B build \
    -D RAPIDJSON_BUILD_DOC=OFF \
    -D RAPIDJSON_BUILD_EXAMPLES=OFF \
    -D RAPIDJSON_BUILD_TESTS=OFF \
    -D RAPIDJSON_BUILD_CXX20=ON \
    -D RAPIDJSON_HAS_STDSTRING=ON \
    && cmake --build build \
    && cmake --install build

# Installing openssl, required by pistache
RUN wget "https://github.com/openssl/openssl/releases/download/openssl-$OPENSSL_VERSION/openssl-$OPENSSL_VERSION.tar.gz" \
    && tar -xzf "openssl-$OPENSSL_VERSION.tar.gz" \
    && cd openssl-$OPENSSL_VERSION \
    && ./config \
    && make \
    && make install
